checkAsserts: true
coverage: false
corpusDir: contracts/echidna/echidna_corpus
seqLen: 3
testLimit: 1000000 # 1 million
shrinkLimit: 100000 # 100k
timeout: 21600 # 6 hours

cryticArgs: # If we add more dependencies they will need to be added as symlinks here!
  [
    "--solc-remaps",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/ @eth-optimism/contracts/=node_modules/@eth-optimism/contracts/ ovm-safeerc20/=node_modules/ovm-safeerc20/",
  ]
