checkAsserts: true
coverage: false
corpusDir: contracts/echidna/echidna_corpus
seqLen: 3
testLimit: 500000
timeout: 3600 # 1 hour

cryticArgs:
  [
    "--solc-remaps",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/ @eth-optimism/contracts/=node_modules/@eth-optimism/contracts/ ovm-safeerc20/=node_modules/ovm-safeerc20/",
  ]
