checkAsserts: true
coverage: false
corpusDir: contracts/echidna/echidna_corpus
seqLen: 5
testLimit: 2000000 # 2 million
shrinkLimit: 200000 # 200k
timeout: 21600 # 6 hours
stopOnFail: true # We want CI to end once we find and shrink on a failing assert.

cryticArgs: # If we add more dependencies they will need to be added as symlinks here!
  [
    "--solc-remaps",
    "@openzeppelin/=node_modules/@openzeppelin/ @eth-optimism/=node_modules/@eth-optimism/ ovm-safeerc20/=node_modules/ovm-safeerc20/",
  ]
