checkAsserts: true
coverage: false
corpusDir: null
seqLen: 3
testLimit: 100000 # 100k
shrinkLimit: 10000 # 10k
timeout: 3600 # 1 hour
stopOnFail: true # We want CI to end once we find and shrink on a failing assert.

cryticArgs: # If we add more dependencies they will need to be added as symlinks here!
  [
    "--solc-remaps",
    "@openzeppelin/=node_modules/@openzeppelin/ @eth-optimism/=node_modules/@eth-optimism/ ovm-safeerc20/=node_modules/ovm-safeerc20/",
  ]
