checkAsserts: true
coverage: false
corpusDir: null
seqLen: 3
testLimit: 50000 # 50k
shrinkLimit: 5000 # 5k
timeout: 3600 # 1 hour
stopOnFail: true # We want CI to end once we find and shrink on a failing assert.

cryticArgs: # If we add more dependencies they will need to be added as symlinks here!
  [
    "--solc-remaps",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/ @eth-optimism/contracts/=node_modules/@eth-optimism/contracts/ ovm-safeerc20/=node_modules/ovm-safeerc20/",
  ]
