checkAsserts: true
coverage: false
corpusDir: contracts/echidna/echidna_corpus
seqLen: 3
testLimit: 100000 # 100k
shrinkLimit: 100000 # 100k
timeout: 21600 # 6 hours
stopOnFail: true # We want CI to end once we find and shrink on a failing assert.

cryticArgs: # If we add more dependencies they will need to be added as symlinks here!
  [
    "--solc-remaps",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/ @eth-optimism/contracts/=node_modules/@eth-optimism/contracts/ ovm-safeerc20/=node_modules/ovm-safeerc20/",
  ]
