name: Update Nova Docs
on:
  push:
    paths:
      - "docs/README.md"

jobs:
  update-nova-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger rebuild in @rari-capital/docs repo
        run: curl -XPOST -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/rari-capital/docs/actions/workflows/update-nova-docs.yml/dispatches --data '{"ref": "master"}'