name: Tests

on: [push, pull_request]

jobs:
  vm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Compile contracts
        run: npm run compile

      - name: Run unit tests
        run: npm run unit-tests

      - name: Run unit tests with coverage
        run: CI= npm run coverage # Unset CI variable so the gas changes don't fail the step

      - name: Upload report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # This is passed by Github, don't worry about setting this.

      - name: Run Codechecks
        run: npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}

  ovm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone the Optimism Monorepo
        working-directory: ../
        run: git clone https://github.com/ethereum-optimism/optimism.git

      - name: Build Optimism ops
        working-directory: ../optimism/ops
        run: ./scripts/build-ci.sh

      - name: Bring Optimism ops up and wait for the sequencer to be ready
        working-directory: ../optimism/ops
        run: docker-compose up -d && ./scripts/wait-for-sequencer.sh

      - name: Run integration tests
        run: |
          npm install
          npm run compile
          npm run integration-tests
