name: Tests

on: [push]

jobs:
  vm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run the tests
        run: |
          npm install
          npm run compile
          npm run vm-test

      - name: Run codechecks
        run: npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}

  ovm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone the Optimism Monorepo
        working-directory: ../
        # TODO: Update this to use master once revert reasons feature is merged.
        run: git clone --branch feat/geth-revert-reasons https://github.com/ethereum-optimism/optimism.git

      - name: Build Optimism ops
        working-directory: ../optimism/ops
        run: ./scripts/build-ci.sh

      - name: Bring Optimism ops up and wait for the sequencer to be ready
        working-directory: ../optimism/ops
        run: docker-compose up -d && ./scripts/wait-for-sequencer.sh

      - name: Run the tests
        run: |
          npm install
          npm run compile
          npm run full-test
