name: Tests

on: [push, pull_request]

jobs:
  vm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests + tests with code coverage
        run: |
          npm install
          npm run compile
          npm run vm-test
          CI= npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

      - name: Run codechecks
        run: npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}

  ovm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone the Optimism Monorepo
        working-directory: ../
        run: git clone https://github.com/ethereum-optimism/optimism.git

      - name: Build Optimism ops
        working-directory: ../optimism/ops
        run: ./scripts/build-ci.sh

      - name: Bring Optimism ops up and wait for the sequencer to be ready
        working-directory: ../optimism/ops
        run: docker-compose up -d && ./scripts/wait-for-sequencer.sh

      - name: Run integration tests
        run: |
          npm install
          npm run compile
          npm run ovm-test
